// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCprbWbytVhumSRyC3uTjLWf9hrAjBVo0A',
    appId: '1:647287839038:web:81a6e1ec1d446197a6f46f',
    messagingSenderId: '647287839038',
    projectId: 'quran-habal',
    authDomain: 'quran-habal.firebaseapp.com',
    storageBucket: 'quran-habal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl-HXpo5A3Gs5rhKMVr2aYgeHuNPLYn8Q',
    appId: '1:647287839038:android:8f7702d50541ea58a6f46f',
    messagingSenderId: '647287839038',
    projectId: 'quran-habal',
    storageBucket: 'quran-habal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl2hJuJKKwtLoamkU3wPFkk3Ow2wKiIQ0',
    appId: '1:647287839038:ios:257a539fe70932f0a6f46f',
    messagingSenderId: '647287839038',
    projectId: 'quran-habal',
    storageBucket: 'quran-habal.firebasestorage.app',
    iosBundleId: 'com.example.quranHabal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl2hJuJKKwtLoamkU3wPFkk3Ow2wKiIQ0',
    appId: '1:647287839038:ios:257a539fe70932f0a6f46f',
    messagingSenderId: '647287839038',
    projectId: 'quran-habal',
    storageBucket: 'quran-habal.firebasestorage.app',
    iosBundleId: 'com.example.quranHabal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCprbWbytVhumSRyC3uTjLWf9hrAjBVo0A',
    appId: '1:647287839038:web:0f18d357a35e640da6f46f',
    messagingSenderId: '647287839038',
    projectId: 'quran-habal',
    authDomain: 'quran-habal.firebaseapp.com',
    storageBucket: 'quran-habal.firebasestorage.app',
  );
}
